### PR TITLE
Added Monoid a => Monoid (RE s a) instance

### PR DESCRIPTION
**Pull request by mitchellwrosen**

### CODE REVIEW

**Comment by feuerbach** [comment]
Why is this needed?

This is not a canonical instance; other instances are possible (e.g. generated by `*>`, `<*`, or `<|>`). You can get them using newtypes from https://hackage.haskell.org/package/reducers

**Comment by mitchellwrosen** [comment]
Not canonical, but it seemed convenient, e.g. to express a float regex as
```haskell
float :: RE Char Float
float = read <$> (some isDigit <> string "." <> some isDigit)
```
rather than
```haskell
float :: RE Char Float
float = read <$> ((\a b c -> a <> b <> c) <$> some isDigit <*> string "." <*> some isDigit)
```
You can already use `*>`, `<*`, or `<|>` explicitly to chain `RE`s together, rather than use that particular Monoid instance, no?

Can you give an example of using reducers?

**Comment by feuerbach** [comment]
This does look nice, but for a (human) reader it may be not obvious what this code does, precisely because there are several possible Monoid instances.

With reducers you'd write

``` haskell
getApp $ Ap (some isDigit) <> Ap (string ".") <> Ap (some isDigit)
```

which I certainly wouldn't advocate in this case. It's more for a case when you have some monoidal code (a fold, perhaps?) that you want to run with `RE`s.

The way it has to be written right now seems looks best to me so far, exactly because it's explicit; esp. if you named the variables something more meaningful than abc. So I am not convinced so far.

**Comment by mitchellwrosen** [comment]
Fair enough. I personally think part of learning the `RE` API is learning what each of its combinators do. For example, I could argue that Set should not have a Monoid instance because how am I supposed to know that `<>` = `S.union`? It could just as easily reduce to the leftmost set of exactly 4 elements.

**Comment by treeowl** [comment]
Because <> being binary union for Set is obvious (the only other natural
choice for a semigroup operation, intersection, lacks a neutral), whereas
it being the lifted monoid for RE is non-obvious. If I had to pick one, I'd
probably pick *>, because that's the operation expressed by juxtaposition
in traditional regular expressions. My second thought would probably be
<|>. You can get the lifted monoid most obviously by lifting the monoid, so
just do that.

**Comment by mitchellwrosen** [comment]
By that logic, should there not be a Monoid instance on Reducer from lexer-applicative? It uses one of many valid Monoid instances of the underlying RE.

**Comment by feuerbach** [comment]
> I personally think part of learning the RE API is learning what each of its combinators do.

As the docs say,

> Regular expressions can be built using Functor, Applicative and Alternative instances in the following natural way: ...

The instances for these classes are indeed natural if you are familiar with these classes; the Monoid instance is not.

> For example, I could argue that Set should not have a Monoid instance because how am I supposed to know that <> = S.union?

The Set instance is sort of natural, but the Map one (which is arbitrarily left-biased) isn't.

But if you are arguing *for* S.`union`, then `<|>` for regexps is much closed to that!

> It could just as easily reduce to the leftmost set of exactly 4 elements.

I don't see how you could make that a valid Monoid.

**Comment by mitchellwrosen** [comment]
> I don't see how you could make that a valid Monoid.

I meant something like this dumb instance:

    instance Monoid (Set a) where
        mempty = S.empty
        s1 `mappend` s2 | S.size s1 == 0 = s2
        s1 `mappend` s2 | S.size s2 == 0 = s1
        s1 `mappend` s2 | S.size s1 == 4 = s1
        _ `mappend` s2 = s2

**Comment by feuerbach** [comment]
Ok, that works.

**Comment by mitchellwrosen** [comment]
Do you think a custom combinator like `(<+>) :: Monoid a => RE s a -> RE s a -> RE s a` would be appropriate? Or is that just useless noise?

**Comment by feuerbach** [comment]
I still don't understand what problem you're trying to solve. Does this pattern come up often enough in your project? Then you can define this combinator right there.

**Comment by mitchellwrosen** [comment]
Ok, well you can close this pull request, then.

**Pull request closed without merging**
